/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbh;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Admin
 */
public class DoiMK extends javax.swing.JFrame {

    /**
     * Creates new form DangKyTaiKhoan1
     */
    
    public DoiMK() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_DangKy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxt_XacNhanMKmoi = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxt_MKmoi = new javax.swing.JPasswordField();
        jcb_MatKhau = new javax.swing.JCheckBox();
        jcb_XacNhanMK = new javax.swing.JCheckBox();
        jcb_MatKhau1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jtxt_TK = new javax.swing.JTextField();
        jtxt_MKcu = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbtn_DangKy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn_DangKy.setText("Đổi mật khẩu");
        jbtn_DangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_DangKyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ĐĂNG KÝ TÀI KHOẢN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Mật khẩu cũ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Mật khẩu mới");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Xác nhận mật khẩu mới");

        jcb_MatKhau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcb_MatKhau.setText("Hiển thị mật khẩu");
        jcb_MatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_MatKhauActionPerformed(evt);
            }
        });

        jcb_XacNhanMK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcb_XacNhanMK.setText("Hiển thị mật khẩu");
        jcb_XacNhanMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_XacNhanMKActionPerformed(evt);
            }
        });

        jcb_MatKhau1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcb_MatKhau1.setText("Hiển thị mật khẩu");
        jcb_MatKhau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_MatKhau1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Tên tài khoản");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcb_MatKhau1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxt_MKcu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_XacNhanMKmoi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_MKmoi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_TK, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jcb_XacNhanMK, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcb_MatKhau, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(102, 102, 102))))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jbtn_DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_TK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_MKcu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_MatKhau1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_MKmoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_MatKhau)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_XacNhanMKmoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_XacNhanMK)
                .addGap(18, 18, 18)
                .addComponent(jbtn_DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jbtn_DangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_DangKyActionPerformed
        String TK = jtxt_TK.getText();
        String MKcu = jtxt_MKcu.getText();
        String MKmoi = jtxt_MKmoi.getText();
        String XN_MKmoi = jtxt_XacNhanMKmoi.getText();
        try {
                ResultSet rs = MysqlConn.query("{ call USP_USER(?, ?)}",TK,MKcu);
                
                if (rs.next() == true) {
                    if (MKcu.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập mật khẩu cũ!", "Thông báo",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (MKcu.equals(jtxt_MKmoi)) {
            JOptionPane.showConfirmDialog(this, "Mật khẩu mới không chính xác!", "Thông báo",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (MKmoi.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập mật khẩu mới!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (XN_MKmoi.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng xác nhận lại mật khẩu mới!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else { 
        try {
                if (!(jtxt_MKmoi.getText().equals(jtxt_XacNhanMKmoi.getText()))) {
                    JOptionPane.showConfirmDialog(this, "Vui lòng kiểm tra lại mật khẩu!", "Thông báo", 
                            JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                PreparedStatement pre = MysqlConn.nonQuery("update nhanvien set matkhau = ? where manv = ?",MKmoi,TK);
                
                int roweff = pre.executeUpdate();
                if (roweff > 0) {
                    JOptionPane.showConfirmDialog(this, "Đổi mật khẩu thành công!", "Thông báo", 
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
                      
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showConfirmDialog(this, "Đổi mật khẩu không thành công!", "Thông báo", 
                            JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
        }
                }
                
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
            JOptionPane.showConfirmDialog(this, "Mật khẩu cũ không chính xác!", "Thông báo",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jbtn_DangKyActionPerformed

    private void jcb_MatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_MatKhauActionPerformed
        if (jcb_MatKhau.isSelected()) {           
            jtxt_MKmoi.setEchoChar((char)0);
//            jcbxShowPass.setText("Ẩn mật khẩu");
        }else       
            jtxt_MKmoi.setEchoChar('*');
//            jcbxShowPass.setText("Hiển thị mật khẩu");
    }//GEN-LAST:event_jcb_MatKhauActionPerformed

    private void jcb_XacNhanMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_XacNhanMKActionPerformed
        if (jcb_XacNhanMK.isSelected()) {           
            jtxt_XacNhanMKmoi.setEchoChar((char)0);
//            jcbxShowPass.setText("Ẩn mật khẩu");
        }else       
            jtxt_XacNhanMKmoi.setEchoChar('*');
//            jcbxShowPass.setText("Hiển thị mật khẩu");
    }//GEN-LAST:event_jcb_XacNhanMKActionPerformed

    private void jcb_MatKhau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_MatKhau1ActionPerformed
        if (jcb_MatKhau1.isSelected()) {           
            jtxt_MKcu.setEchoChar((char)0);
//            jcbxShowPass.setText("Ẩn mật khẩu");
        }else       
            jtxt_MKcu.setEchoChar('*');
//            jcbxShowPass.setText("Hiển thị mật khẩu");
    }//GEN-LAST:event_jcb_MatKhau1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DangKyTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtn_DangKy;
    private javax.swing.JCheckBox jcb_MatKhau;
    private javax.swing.JCheckBox jcb_MatKhau1;
    private javax.swing.JCheckBox jcb_XacNhanMK;
    private javax.swing.JPasswordField jtxt_MKcu;
    private javax.swing.JPasswordField jtxt_MKmoi;
    private javax.swing.JTextField jtxt_TK;
    private javax.swing.JPasswordField jtxt_XacNhanMKmoi;
    // End of variables declaration//GEN-END:variables
}
