/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbh;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class ttKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form ttKhachHang
     */
    
    
    
    public ttKhachHang() {
        initComponents();
        setLocationRelativeTo(null);
    }
    private void LoadData() {
        try {
                ResultSet rs = MysqlConn.query("select * from khachhang");
                DefaultTableModel model = (DefaultTableModel)jTable_KhachHang.getModel();
                model.setRowCount(0);
                while (rs.next()) {    
                    model.addRow(new Object[]{  
                        rs.getString("MaKH"),
                        rs.getString("TenKH"),
                        rs.getString("DiaChi"),
                        rs.getString("TongTien")});  
                }
                
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_KhachHang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxt_MaKH = new javax.swing.JTextField();
        jtxt_TenKH = new javax.swing.JTextField();
        jtxt_DiaChi = new javax.swing.JTextField();
        jtxt_TongTien = new javax.swing.JTextField();
        jtxt_TimKiem = new javax.swing.JTextField();
        jbtn_TimKiem = new javax.swing.JButton();
        jbtn_AddKH = new javax.swing.JButton();
        jbtn_UpdateKH = new javax.swing.JButton();
        jbtn_Reset = new javax.swing.JButton();
        jbtn_Delete = new javax.swing.JButton();
        jbtn_Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtn_return = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Khách hàng"));

        jTable_KhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Địa chỉ", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_KhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_KhachHang);
        if (jTable_KhachHang.getColumnModel().getColumnCount() > 0) {
            jTable_KhachHang.getColumnModel().getColumn(2).setPreferredWidth(250);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã khách hàng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tên khách hàng");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Địa chỉ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tổng tiền");

        jbtn_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_TimKiem.setText("Tìm kiếm");
        jbtn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(24, 24, 24)
                            .addComponent(jtxt_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2)
                        .addComponent(jtxt_MaKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtxt_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtn_TimKiem)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(jtxt_DiaChi)))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxt_TimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxt_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jbtn_TimKiem)))
                .addGap(19, 19, 19))
        );

        jbtn_AddKH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_AddKH.setText("Add New");
        jbtn_AddKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_AddKHActionPerformed(evt);
            }
        });

        jbtn_UpdateKH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_UpdateKH.setText("Update");
        jbtn_UpdateKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_UpdateKHActionPerformed(evt);
            }
        });

        jbtn_Reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Reset.setText("Reset");
        jbtn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ResetActionPerformed(evt);
            }
        });

        jbtn_Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Delete.setText("Delete");
        jbtn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_DeleteActionPerformed(evt);
            }
        });

        jbtn_Exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Exit.setText("Exit");
        jbtn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("THÔNG TIN KHÁCH HÀNG");

        jbtn_return.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_return.setText("<<");
        jbtn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_returnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jbtn_AddKH)
                .addGap(30, 30, 30)
                .addComponent(jbtn_UpdateKH, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jbtn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                .addComponent(jbtn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jbtn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jbtn_return)
                .addGap(216, 216, 216)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jbtn_return))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_AddKH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_UpdateKH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ExitActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "Thông báo", 
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION) {
             System.exit(0);
        }
    }//GEN-LAST:event_jbtn_ExitActionPerformed

    private void jbtn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ResetActionPerformed
        jtxt_MaKH.setText(null);
        jtxt_TenKH.setText(null);
        jtxt_DiaChi.setText(null);
        jtxt_TongTien.setText(null);
    }//GEN-LAST:event_jbtn_ResetActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       LoadData();
    }//GEN-LAST:event_formWindowOpened

    private void jTable_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_KhachHangMouseClicked
            Integer rowSelect = jTable_KhachHang.getSelectedRow();
        jtxt_MaKH.setText(jTable_KhachHang.getModel().getValueAt(rowSelect, 0).toString());
        jtxt_TenKH.setText(jTable_KhachHang.getModel().getValueAt(rowSelect, 1).toString());
        jtxt_DiaChi.setText(jTable_KhachHang.getModel().getValueAt(rowSelect, 2).toString());
        jtxt_TongTien.setText(jTable_KhachHang.getModel().getValueAt(rowSelect, 3).toString());        
    }//GEN-LAST:event_jTable_KhachHangMouseClicked

    private void jbtn_AddKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_AddKHActionPerformed
            String MaKH = jtxt_MaKH.getText();
            String TenKH = jtxt_TenKH.getText();
            String DiaChi = jtxt_DiaChi.getText();
            String TongTien = jtxt_TongTien.getText();
         
        if (MaKH.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập vào mã khách hàng!", "Thông báo",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (TenKH.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập vào tên khách hàng!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (DiaChi.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập vào địa chỉ khách hàng!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (TongTien.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập vào tổng số tiền của khách hàng!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }        
        else{    
        try {
                PreparedStatement pre = MysqlConn.nonQuery("insert into khachhang(MaKH, TenKH, DiaChi, TongTien) "
                        + "values (?, ?, ?, ?, ?)",MaKH, TenKH,DiaChi,TongTien);
                int roweff = pre.executeUpdate();
                if (roweff > 0) {
                    LoadData();
                    JOptionPane.showConfirmDialog(this, "Dữ liệu đã được thêm vào!", "Thông Báo", 
                            JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE );
            }
                
        } catch (SQLException e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jbtn_AddKHActionPerformed

    private void jbtn_UpdateKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_UpdateKHActionPerformed
            String MaKH = jtxt_MaKH.getText();
            String TenKH = jtxt_TenKH.getText();
            String DiaChi = jtxt_DiaChi.getText();
            String TongTien = jtxt_TongTien.getText();
        if (MaKH.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn khách hàng!", "Thông báo",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (TenKH.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn khách hàng!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (DiaChi.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn khách hàng!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (TongTien.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn khách hàng!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else{     
        try {
                PreparedStatement pre = MysqlConn.nonQuery("update khachhang set TenKH = ?, DiaChi = ?, TongTien = ? "
                        + "where  MaKH = ?",TenKH,DiaChi,TongTien,MaKH);                        
                
                
                int roweff = pre.executeUpdate();
                if (roweff > 0) {
                    LoadData();
                    JOptionPane.showConfirmDialog(this, "Dữ liệu đã được thay đổi!", "Thông Báo", 
                            JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE );
            }
                
        } catch (SQLException e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jbtn_UpdateKHActionPerformed

    private void jbtn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_DeleteActionPerformed
            String MaKH = jtxt_MaKH.getText();
            String TenKH = jtxt_TenKH.getText();
            String DiaChi = jtxt_DiaChi.getText();
            String TongTien = jtxt_TongTien.getText();
        if (MaKH.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn khách hàng!", "Thông báo",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (TenKH.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn khách hàng!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (DiaChi.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn khách hàng!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (TongTien.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn khách hàng!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else{  
        try {
                PreparedStatement pre = MysqlConn.nonQuery("delete from khachhang where MaKH = ? ",MaKH);    
                if (JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xoá dữ liệu này", "Thông báo", 
                         JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE ) == JOptionPane.NO_OPTION) {                   
                    return;
                }
                
                int roweff = pre.executeUpdate();
                if (roweff > 0) {
                    LoadData();
                    JOptionPane.showConfirmDialog(this, "Dữ liệu đã được xoá!", "Thông Báo", 
                            JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE );
            }
                
        } catch (SQLException e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jbtn_DeleteActionPerformed

    private void jbtn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_TimKiemActionPerformed
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>((DefaultTableModel)jTable_KhachHang.getModel());
        jTable_KhachHang.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + jtxt_TimKiem.getText()));  
    }//GEN-LAST:event_jbtn_TimKiemActionPerformed

    private void jbtn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_returnActionPerformed
        TrangChu tc = new TrangChu();
        this.hide();
        tc.setVisible(true);
    }//GEN-LAST:event_jbtn_returnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ttKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ttKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ttKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ttKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ttKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_KhachHang;
    private javax.swing.JButton jbtn_AddKH;
    private javax.swing.JButton jbtn_Delete;
    private javax.swing.JButton jbtn_Exit;
    private javax.swing.JButton jbtn_Reset;
    private javax.swing.JButton jbtn_TimKiem;
    private javax.swing.JButton jbtn_UpdateKH;
    private javax.swing.JButton jbtn_return;
    private javax.swing.JTextField jtxt_DiaChi;
    private javax.swing.JTextField jtxt_MaKH;
    private javax.swing.JTextField jtxt_TenKH;
    private javax.swing.JTextField jtxt_TimKiem;
    private javax.swing.JTextField jtxt_TongTien;
    // End of variables declaration//GEN-END:variables
}
