/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbh;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class ttNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form ttNhanVien
     */
    
    
    public ttNhanVien() {
        initComponents();
        setLocationRelativeTo(null);
    }
    private void LoadData() {
        try {
                ResultSet rs = MysqlConn.query("SELECT MaNV,TenNV, concat('0', sdt) as sdt, DiaChi, ChucVu, NgayNC FROM nhanvien");
                DefaultTableModel model = (DefaultTableModel)jTable_NhanVien.getModel();
                model.setRowCount(0);
                while(rs.next()){
                model.addRow(new Object[]{
                    rs.getInt("MaNV"),
                    rs.getString("TenNV"),
                    rs.getString("SDT"),
                    rs.getString("DiaChi"),
                    rs.getByte("ChucVu"),
                    rs.getString("NgayNC")});
                }
                
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxt_MaNV = new javax.swing.JTextField();
        jtxt_TenNV = new javax.swing.JTextField();
        jtxt_DiaChiNV = new javax.swing.JTextField();
        jtxt_sđtNV = new javax.swing.JTextField();
        jtxt_TimKiem = new javax.swing.JTextField();
        jbtn_TimKiem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtxt_NgayNhanChuc = new javax.swing.JTextField();
        jSpinner_ChucVu = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_NhanVien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jbtn_AddNV = new javax.swing.JButton();
        jbtn_UpdateNV = new javax.swing.JButton();
        jbtn_ResetNV = new javax.swing.JButton();
        jbtn_DeleteNV = new javax.swing.JButton();
        jbtn_ExitNV = new javax.swing.JButton();
        jbtn_return = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tên nhân viên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Chức vụ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Địa chỉ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Số điện thoại");

        jbtn_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_TimKiem.setText("Tìm kiếm");
        jbtn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_TimKiemActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ngày nhận chức");

        jSpinner_ChucVu.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)1), Byte.valueOf((byte)0), Byte.valueOf((byte)1), Byte.valueOf((byte)1)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(58, 58, 58)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtxt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jtxt_TimKiem)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_TimKiem)
                        .addGap(126, 126, 126))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSpinner_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(54, 54, 54)
                                .addComponent(jtxt_DiaChiNV))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jtxt_NgayNhanChuc)))
                        .addGap(31, 31, 31))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jtxt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(49, 49, 49)
                        .addComponent(jtxt_sđtNV)
                        .addGap(31, 31, 31))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_DiaChiNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_sđtNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtxt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_NgayNhanChuc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_TimKiem)
                    .addComponent(jtxt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Khách hàng"));

        jTable_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Số điện thoại", "Địa chỉ", "Chức vụ", "Ngày nhận chức"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_NhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_NhanVien);
        if (jTable_NhanVien.getColumnModel().getColumnCount() > 0) {
            jTable_NhanVien.getColumnModel().getColumn(3).setPreferredWidth(250);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("THÔNG TIN NHÂN VIÊN");

        jbtn_AddNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_AddNV.setText("Add New");
        jbtn_AddNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_AddNVActionPerformed(evt);
            }
        });

        jbtn_UpdateNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_UpdateNV.setText("Update");
        jbtn_UpdateNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_UpdateNVActionPerformed(evt);
            }
        });

        jbtn_ResetNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_ResetNV.setText("Reset");
        jbtn_ResetNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ResetNVActionPerformed(evt);
            }
        });

        jbtn_DeleteNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_DeleteNV.setText("Delete");
        jbtn_DeleteNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_DeleteNVActionPerformed(evt);
            }
        });

        jbtn_ExitNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_ExitNV.setText("Exit");
        jbtn_ExitNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ExitNVActionPerformed(evt);
            }
        });

        jbtn_return.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_return.setText("<<");
        jbtn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_returnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jbtn_return)
                .addGap(340, 340, 340)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(402, 402, 402))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jbtn_AddNV)
                .addGap(32, 32, 32)
                .addComponent(jbtn_UpdateNV, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jbtn_ResetNV, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_DeleteNV, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jbtn_ExitNV, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jbtn_return))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_AddNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_UpdateNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_ResetNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_DeleteNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_ExitNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_ExitNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ExitNVActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "Thông báo", 
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION) {
             System.exit(0);
        }
    }//GEN-LAST:event_jbtn_ExitNVActionPerformed

    private void jbtn_ResetNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ResetNVActionPerformed
        jtxt_MaNV.setText(null);
        jtxt_TenNV.setText(null);
        jSpinner_ChucVu.setValue(1);
        jtxt_DiaChiNV.setText(null);
        jtxt_NgayNhanChuc.setText(null);
        jtxt_sđtNV.setText(null);
    }//GEN-LAST:event_jbtn_ResetNVActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LoadData();
    }//GEN-LAST:event_formWindowOpened

    private void jTable_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_NhanVienMouseClicked
            Integer rowSelect = jTable_NhanVien.getSelectedRow();
        jtxt_MaNV.setText(jTable_NhanVien.getModel().getValueAt(rowSelect, 0).toString());
        jtxt_TenNV.setText(jTable_NhanVien.getModel().getValueAt(rowSelect, 1).toString());
        jtxt_sđtNV.setText(jTable_NhanVien.getModel().getValueAt(rowSelect, 2).toString());
        jtxt_DiaChiNV.setText(jTable_NhanVien.getModel().getValueAt(rowSelect, 3).toString());
        jSpinner_ChucVu.setValue(jTable_NhanVien.getModel().getValueAt(rowSelect, 4));
        jtxt_NgayNhanChuc.setText(jTable_NhanVien.getModel().getValueAt(rowSelect, 5).toString());
    }//GEN-LAST:event_jTable_NhanVienMouseClicked

    private void jbtn_AddNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_AddNVActionPerformed
            String MaNV = jtxt_MaNV.getText();
            String TenNV = jtxt_TenNV.getText();
            String SDT = jtxt_sđtNV.getText();
//          int SDT = Integer.parseInt(jtxt_sđtNV.getText());
            String DiaChi = jtxt_DiaChiNV.getText();
            int ChucVu = Integer.parseInt(jSpinner_ChucVu.getValue().toString());           
            String NgayNC = jtxt_NgayNhanChuc.getText();
        if (MaNV.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập vào mã nhân viên!", "Thông báo",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (TenNV.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập vào tên nhân viên!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (SDT.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập số điện thoại nhân viên!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (SDT.length() != 10) {
            JOptionPane.showConfirmDialog(this, "Số điện thoại phải 10 chữ số!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (DiaChi.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập vào địa chỉ nhân!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (NgayNC.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập ngày nhận chức!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else{
        try {
                
                PreparedStatement pre = MysqlConn.nonQuery("insert into nhanvien(MaNV, TenNV, SDT, DiaChi, ChucVu, NgayNC, matkhau) "
                        + "values (?, ?, ?, ?, ?, ?, ?)",MaNV,TenNV,SDT,DiaChi,ChucVu,NgayNC,SDT);
                int roweff = pre.executeUpdate();
                if (roweff > 0) {
                    LoadData();
                    JOptionPane.showConfirmDialog(this, "Dữ liệu đã được thêm vào!", "Thông Báo", 
                            JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE );
                }                
        } catch (SQLException e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jbtn_AddNVActionPerformed

    private void jbtn_UpdateNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_UpdateNVActionPerformed
            String MaNV = jtxt_MaNV.getText();
            String TenNV = jtxt_TenNV.getText();
            String SDT = jtxt_sđtNV.getText();
//            int SDT = Integer.parseInt(jtxt_sđtNV.getText());
            String DiaChi = jtxt_DiaChiNV.getText();
            int ChucVu = Integer.parseInt(jSpinner_ChucVu.getValue().toString());           
            String NgayNC = jtxt_NgayNhanChuc.getText();
        if (MaNV.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn nhân viên!", "Thông báo",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (TenNV.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn nhân viên!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (SDT.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn nhân viên!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (SDT.length() != 10) {
            JOptionPane.showConfirmDialog(this, "Số điện thoại phải 10 chữ số!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (DiaChi.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn nhân viên!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (NgayNC.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn nhân viên!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else{            
        try {
                
            
                PreparedStatement pre = MysqlConn.nonQuery("update nhanvien set  TenNV = ?, SDT = ?, DiaChi = ?, ChucVu = ?, NgayNC = ? "
                        + "where MaNV = ?", TenNV, SDT,DiaChi,ChucVu,NgayNC,MaNV);
                        
                int roweff = pre.executeUpdate();
                if (roweff > 0) {
                    LoadData();
                    JOptionPane.showConfirmDialog(this, "Dữ liệu đã được thay đổi!", "Thông Báo", 
                            JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE );
                }                
        } catch (SQLException e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jbtn_UpdateNVActionPerformed

    private void jbtn_DeleteNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_DeleteNVActionPerformed
            String MaNV = jtxt_MaNV.getText();
            String TenNV = jtxt_TenNV.getText();
            String SDT = jtxt_sđtNV.getText();
//            int SDT = Integer.parseInt(jtxt_sđtNV.getText());
            String DiaChi = jtxt_DiaChiNV.getText();
            int ChucVu = Integer.parseInt(jSpinner_ChucVu.getValue().toString());           
            String NgayNC = jtxt_NgayNhanChuc.getText();
        if (MaNV.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn nhân viên!", "Thông báo",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (TenNV.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn nhân viên!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (SDT.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn nhân viên!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (DiaChi.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn nhân viên!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (NgayNC.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn nhân viên!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else{  
        try {
                PreparedStatement pre = MysqlConn.nonQuery("delete from nhanvien where MaNV = ?",MaNV);                       
                

                if (JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xoá dữ liệu này", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE ) == JOptionPane.NO_OPTION) {                   
                    return;
                }
                
                int roweff = pre.executeUpdate();
                if (roweff > 0) {
                    LoadData();
                    JOptionPane.showConfirmDialog(this, "Dữ liệu đã được xoá!", "Thông Báo", 
                            JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE );
                }                
        } catch (SQLException e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jbtn_DeleteNVActionPerformed

    private void jbtn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_TimKiemActionPerformed
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>((DefaultTableModel)jTable_NhanVien.getModel());
        jTable_NhanVien.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + jtxt_TimKiem.getText())); 
    }//GEN-LAST:event_jbtn_TimKiemActionPerformed

    private void jbtn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_returnActionPerformed
        TrangChu tc = new TrangChu();
        this.hide();
        tc.setVisible(true);
    }//GEN-LAST:event_jbtn_returnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ttNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ttNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ttNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ttNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_ChucVu;
    private javax.swing.JTable jTable_NhanVien;
    private javax.swing.JButton jbtn_AddNV;
    private javax.swing.JButton jbtn_DeleteNV;
    private javax.swing.JButton jbtn_ExitNV;
    private javax.swing.JButton jbtn_ResetNV;
    private javax.swing.JButton jbtn_TimKiem;
    private javax.swing.JButton jbtn_UpdateNV;
    private javax.swing.JButton jbtn_return;
    private javax.swing.JTextField jtxt_DiaChiNV;
    private javax.swing.JTextField jtxt_MaNV;
    private javax.swing.JTextField jtxt_NgayNhanChuc;
    private javax.swing.JTextField jtxt_TenNV;
    private javax.swing.JTextField jtxt_TimKiem;
    private javax.swing.JTextField jtxt_sđtNV;
    // End of variables declaration//GEN-END:variables
}
