/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbh;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Admin
 */
public class ttThietBi extends javax.swing.JFrame {

    /**
     * Creates new form ttThietBi
     */
   
    
    public ttThietBi() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void LoadData() {
        try {
                ResultSet rs = MysqlConn.query("select * from sanpham");
                DefaultTableModel model = (DefaultTableModel)jTable_SanPham.getModel();
                model.setRowCount(0);
                while (rs.next()) {                    
                    model.addRow(new Object[]{
                        rs.getString("MaSP"),
                        rs.getString("TenSP"),
                        rs.getInt("SL"),
                        rs.getInt("GiaGoc"),
                        rs.getString("Loai")});                   
                    
                }
                
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtn_Update = new javax.swing.JButton();
        jbtn_Delete = new javax.swing.JButton();
        jbtn_Reset = new javax.swing.JButton();
        jbtn_Add = new javax.swing.JButton();
        jbtn_Exit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_SanPham = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jtxt_MaSP = new javax.swing.JTextField();
        jtxt_TenSP = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jtxt_GiaGoc = new javax.swing.JTextField();
        jtxt_Loai = new javax.swing.JTextField();
        jSpinner_SoLuong = new javax.swing.JSpinner();
        jtxt_TimKiem = new javax.swing.JTextField();
        jbtn_TimKiem = new javax.swing.JButton();
        jbtn_return = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("THÔNG TIN LINH KIỆN");

        jbtn_Update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Update.setText("Update");
        jbtn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_UpdateActionPerformed(evt);
            }
        });

        jbtn_Delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Delete.setText("Delete");
        jbtn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_DeleteActionPerformed(evt);
            }
        });

        jbtn_Reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Reset.setText("Reset");
        jbtn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ResetActionPerformed(evt);
            }
        });

        jbtn_Add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Add.setText("Add New");
        jbtn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_AddActionPerformed(evt);
            }
        });

        jbtn_Exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_Exit.setText("Exit");
        jbtn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ExitActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản phẩm"));

        jTable_SanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã LK", "Tên LK", "Số lượng", "Giá gốc", "Loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_SanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_SanPham);
        if (jTable_SanPham.getColumnModel().getColumnCount() > 0) {
            jTable_SanPham.getColumnModel().getColumn(0).setPreferredWidth(160);
            jTable_SanPham.getColumnModel().getColumn(1).setPreferredWidth(370);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setText("Loại");

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel58.setText("Số lượng ");

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel59.setText("Mã sản phẩm ");

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel60.setText("Tên sản phẩm");

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel61.setText("Giá gốc");

        jSpinner_SoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));

        jbtn_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_TimKiem.setText("Tìm kiếm");
        jbtn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel59)
                    .addComponent(jLabel60)
                    .addComponent(jLabel58))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_TenSP, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                            .addComponent(jtxt_MaSP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel61)
                            .addComponent(jLabel56))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_Loai, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(jtxt_GiaGoc)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jSpinner_SoLuong)
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtn_TimKiem)))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxt_GiaGoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel61))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxt_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel56))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_TimKiem)
                            .addComponent(jSpinner_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel58)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel59))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel60))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jbtn_return.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtn_return.setText("<<");
        jbtn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_returnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jbtn_return)
                        .addGap(255, 255, 255)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(319, 319, 319))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jbtn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jbtn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jbtn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231)
                        .addComponent(jbtn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jbtn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jbtn_return))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ExitActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "Thông báo", 
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtn_ExitActionPerformed

    private void jbtn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ResetActionPerformed
        jtxt_MaSP.setText(null);
        jtxt_TenSP.setText(null);
        jtxt_GiaGoc.setText(null);
        jtxt_Loai.setText(null);       
        jSpinner_SoLuong.setValue(0);;
    }//GEN-LAST:event_jbtn_ResetActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LoadData();
    }//GEN-LAST:event_formWindowOpened

    private void jTable_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_SanPhamMouseClicked
            Integer rowSelect = jTable_SanPham.getSelectedRow();
        jtxt_MaSP.setText(jTable_SanPham.getModel().getValueAt(rowSelect, 0).toString());
        jtxt_TenSP.setText(jTable_SanPham.getModel().getValueAt(rowSelect, 1).toString());
        jSpinner_SoLuong.setValue(jTable_SanPham.getModel().getValueAt(rowSelect, 2));
        jtxt_GiaGoc.setText(jTable_SanPham.getModel().getValueAt(rowSelect, 3).toString());
        jtxt_Loai.setText(jTable_SanPham.getModel().getValueAt(rowSelect, 4).toString());       
    }//GEN-LAST:event_jTable_SanPhamMouseClicked

    private void jbtn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_AddActionPerformed
            String MaSP = jtxt_MaSP.getText();
            String TenSP = jtxt_TenSP.getText();
            String GiaGoc = jtxt_GiaGoc.getText();
            String Loai = jtxt_Loai.getText();           
            String soLuong = jSpinner_SoLuong.getValue().toString();
        if (MaSP.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập mã sản phẩm!", "Thông báo",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (TenSP.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập vào tên sản phẩm!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (GiaGoc.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập vào giá sản phẩm!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (Loai.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập vào loại sản phẩm!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (soLuong.equals("0")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập vào số lượng sản phẩm!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else {
        try {
                PreparedStatement pre = MysqlConn.nonQuery("insert into sanpham(MaSP, TenSP, SL, GiaGoc, Loai) "
                        + "values (?, ?, ?, ?, ?)",MaSP,TenSP,soLuong,GiaGoc,Loai);

                int roweff = pre.executeUpdate();
                if (roweff > 0) {                    
                    LoadData();
                    JOptionPane.showConfirmDialog(this, "Dữ liệu đã được thêm vào!", "Thông báo", 
                            JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                }
                
        } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(this, "Lỗi kết nối!");
                Logger.getLogger(ttThietBi.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jbtn_AddActionPerformed

    private void jbtn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_UpdateActionPerformed
            String MaSP = jtxt_MaSP.getText();
            String TenSP = jtxt_TenSP.getText();
            String GiaGoc = jtxt_GiaGoc.getText();
            String Loai = jtxt_Loai.getText();           
            String soLuong = jSpinner_SoLuong.getValue().toString();
        if (MaSP.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn sản phẩm!", "Thông báo",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (TenSP.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn sản phẩm!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (GiaGoc.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn sản phẩm!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (Loai.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn sản phẩm!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (soLuong.equals("0")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng nhập vào số lượng sản phẩm!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else{
        try {
                
                PreparedStatement pre = MysqlConn.nonQuery("update sanpham set TenSP = ?, SL = ?, GiaGoc = ?, Loai = ?"
                        + "where MaSP = ?",TenSP,soLuong,GiaGoc,Loai,MaSP);                        
                            
                
                int roweff = pre.executeUpdate();
                if (roweff > 0) {                    
                    LoadData();
                    JOptionPane.showConfirmDialog(this, "Dữ liệu đã được thay đổi!", "Thông báo", 
                            JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                }
                
        } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(this, "Lỗi kết nối!");
                Logger.getLogger(ttThietBi.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jbtn_UpdateActionPerformed

    private void jbtn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_DeleteActionPerformed
            String MaSP = jtxt_MaSP.getText();
            String TenSP = jtxt_TenSP.getText();
            String GiaGoc = jtxt_GiaGoc.getText();
            String Loai = jtxt_Loai.getText();           
            String soLuong = jSpinner_SoLuong.getValue().toString();
        if (MaSP.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn sản phẩm!", "Thông báo",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (TenSP.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn sản phẩm!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (GiaGoc.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn sản phẩm!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else if (Loai.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng chọn sản phẩm!", "Thông báo", 
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        else { 
        try {
                
                PreparedStatement pre = MysqlConn.nonQuery("delete from sanpham where MaSP = ?",MaSP);                        
                          
                                
                if (JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xoá dữ liệu này", "Thông báo", 
                         JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE ) == JOptionPane.NO_OPTION) {                   
                    return;
                }
                
                int roweff = pre.executeUpdate();
                if (roweff > 0) {                    
                    LoadData();
                    JOptionPane.showConfirmDialog(this, "Dữ liệu đã được xoá!", "Thông báo", 
                            JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                }
                
        } catch (SQLException ex) {
                JOptionPane.showConfirmDialog(this, "Lỗi kết nối!");
                Logger.getLogger(ttThietBi.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jbtn_DeleteActionPerformed

    private void jbtn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_TimKiemActionPerformed

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>((DefaultTableModel)jTable_SanPham.getModel());
        jTable_SanPham.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + jtxt_TimKiem.getText()));        
        
    }//GEN-LAST:event_jbtn_TimKiemActionPerformed

    private void jbtn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_returnActionPerformed
        TrangChu tc = new TrangChu();
        this.hide();
        tc.setVisible(true);
    }//GEN-LAST:event_jbtn_returnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ttThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ttThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ttThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ttThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ttThietBi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_SoLuong;
    private javax.swing.JTable jTable_SanPham;
    private javax.swing.JButton jbtn_Add;
    private javax.swing.JButton jbtn_Delete;
    private javax.swing.JButton jbtn_Exit;
    private javax.swing.JButton jbtn_Reset;
    private javax.swing.JButton jbtn_TimKiem;
    private javax.swing.JButton jbtn_Update;
    private javax.swing.JButton jbtn_return;
    private javax.swing.JTextField jtxt_GiaGoc;
    private javax.swing.JTextField jtxt_Loai;
    private javax.swing.JTextField jtxt_MaSP;
    private javax.swing.JTextField jtxt_TenSP;
    private javax.swing.JTextField jtxt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
